Feat/complete registration form
FGA-EPS-2024-2-Infantio/frontend pull request #12
Opened 2024-11-26 23:09 UTC by HenriPucci

2024-12-01 20:20 UTC, LucasLopesFrazao requested changes
Telefone Hospital e Telefone Médico sem mascarás

Botão de enviar deve ficar bloqueado até aceitar os dois termos

Ao enviar os dados, colocar uma notificação (usa o que já temos, o toastify) falando que tudo deu certo e atualizar a página, para ir para a mensagem de Formulário já preenchido, pois quando eu cliquei para enviar, eu vi que deu certo, vendo no bd, mas para o usuário na tela ficou o mesmo.

Melhorar o design do formulário já preenchido, coloca um container branco no meio com o nome do aluno e tal (coisa básica, só para não ficar um texto em preto em cima).

Faltou colocar os dados preenchidos lá dentro do aluno, quando vamos no CRUD De alunos e entrarmos em um aluno em especifico.

Nessa mesma tela, lá no menu de ações, o botão de "copiar link" não está copiando o link correto, para o envio dos pais (/formulario-matricula/<id_aluno>/

2024-12-01 20:20 UTC, LucasLopesFrazao commented on frontend/src/app/(auth)/alunos/[studentId]/page.tsx
> +    console.log(student);
Ops

2024-12-01 20:20 UTC, LucasLopesFrazao commented on frontend/src/app/formulario-matricula/[studentId]/page.tsx
> -                Autorizo que fotos e filmagens que incluam meu/minha filho(a) sejam feitas e utilizadas pela equipe da escola para fins pedagógicos, para publicação no site/da escola/da turma, e para
Vamos manter exatamente o texto de autorização

2024-12-01 20:20 UTC, LucasLopesFrazao commented on frontend/src/app/formulario-matricula/[studentId]/page.tsx
> -                Assumo inteira responsabilidade pelas informações e pelo pagamento.
Vamos manter o mesmo texto de responsabilidade

2024-12-06 12:39 UTC, hugorochaffs commented on frontend/src/app/(auth)/alunos/[studentId]/page.tsx
> +    console.log(student);
removido

2024-12-06 12:40 UTC, hugorochaffs commented on frontend/src/app/formulario-matricula/[studentId]/page.tsx
> -                Autorizo que fotos e filmagens que incluam meu/minha filho(a) sejam feitas e utilizadas pela equipe da escola para fins pedagógicos, para publicação no site/da escola/da turma, e para
ok

2024-12-07 23:49 UTC, LucasLopesFrazao approved these changes

2024-12-07 23:49 UTC, merged